### ISSUE TITLE
Competitive Advantages Section

### ISSUE THREAD

**Issue by mattbencsik** [mattbencsik/isdevelopmentmethods#5]
500 words max for this section as we need to keep under 2000 words for report. 

Ideas: pick 5 main competitive advantages and discuss in detail (i.e. 100 words for each)

Thoughts???

**Comment by elyssaberry1** [comment]
Came up with 6 potential competitive advantages to be included

-Increased Customer Satisfaction (through profile matching, customer data collection and personalised service)
-Speed (improved call routing and redirection will lend itself to an efficient sales process, per-call routing duration will be decreased, interactive voice response will manage the call routing during busier periods) 
-Increased Sales Performance (providing customers with RMs with appropriate knowledge makes the RM's more convincing, hence more likely to make a sale)
- Skill Enhancement (by providing RM's with a script, customer profile data and outbound calling. Also tracks their performance and gives them a visual medium to encourage improvement)
- Cost Effective (by reducing per-call handling time)
- Customer Relationship Management (more loyal/regular customers are prioritised and given RMs with higher skill scores)

**Comment by erikatheagross** [comment]
I'll add that info to the competitive advantage and start writing it up
